Fix Buffer when storing arrays
FluxML/Zygote.jl pull request #1134
Opened 2021-12-13 04:30 UTC by avik-pal

MWE:

```julia
using Zygote, Flux

struct MultiParallelNet{L}
    layers::L

    function MultiParallelNet(args...)
        layers = tuple(args...)
        return new{typeof(layers)}(layers)
    end

    MultiParallelNet(layers::Tuple) = new{typeof(layers)}(layers)

    MultiParallelNet(layers::Vector) = MultiParallelNet(layers...)
end

Flux.@functor MultiParallelNet

function (mpn::MultiParallelNet)(x::Union{Tuple,Vector})
    buf = Zygote.Buffer([])
    for l in mpn.layers
        push!(buf, l(x...))
    end
    return copy(buf)
end

function (mpn::MultiParallelNet)(args...)
    buf = Zygote.Buffer([])
    for l in mpn.layers
        push!(buf, l(args...))
    end
    return copy(buf)
end

mpn = MultiParallelNet(Dense(1, 1), Dense(1, 1))
x = rand(Float32, 1, 1)
gradient(() -> sum(vcat(mpn((x,))...)), Flux.params(mpn))
```

```julia
ERROR: ArgumentError: indexed assignment with a single value to possibly many locations is not supported; perhaps use broadcasting `.=` instead?
```

2021-12-13 07:03 UTC, DhairyaLGandhi approved these changes
Seems fine but needs a test

2021-12-13 14:07 UTC, ToucheSir commented
Existing buffer test failure needs to be resolved as well...

2021-12-13 14:23 UTC, ToucheSir requested changes
https://github.com/FluxML/Zygote.jl/blob/master/test/gradcheck.jl#L1428 this one

2021-12-13 17:42 UTC, avik-pal commented
Added tests and fixed the mentioned test case.

The other failures seem to be unrelated:
```
ERROR: LoadError: InitError: could not load symbol "LLVMExtraInitializeAllTargets":
/opt/hostedtoolcache/julia/nightly/x64/bin/julia: undefined symbol: LLVMExtraInitializeAllTargets
```

2021-12-13 18:00 UTC, ToucheSir approved these changes
Yeah, something is screwy with the CUDA dep resolving and I'm not sure why, perhaps package server lag causing issues? Buffer tests look good though, thanks!

2021-12-16 18:16 UTC, avik-pal commented
bump

2021-12-16 18:37 UTC, DhairyaLGandhi approved these changes

2021-12-16 18:37 UTC, DhairyaLGandhi commented on src/lib/buffer.jl
> +  function copy_sensitivity(b̄::Union{Tuple,Vector{T}}) where {T<:AbstractArray}
```suggestion
  function copy_sensitivity(b̄::Union{Tuple,AbstractVector{T}}) where {T<:AbstractArray}
```

Fwiw,  `Buffer` mimics `similar` more than it does a literal array; and `similar(::Tuple)` would be an error.

2021-12-25 03:42 UTC, ToucheSir commented
bors r+

2021-12-25 04:06 UTC, merged